services:
  superar1_sgpro:
    build: .

    container_name: superar1_sgpro

    restart: unless-stopped

    ports:
      - "8085:80"

    networks:
      - moodle_net

networks:
  moodle_net:
    external: true
